.onLoad = function (libname, pkgname) {
    # LRU cache of 4gb of maximum size and a day of maximum age of a translation
    cm <- cachem::cache_mem(max_size = 4096 * 1024^2, max_age = 86400, evict='lru')

    .getNCBIDatabasesLinks <<- memoise::memoise(.getNCBIDatabasesLinks, cache = cm)
    getNCBIGene2NCBIProtein <<- memoise::memoise(getNCBIGene2NCBIProtein, cache = cm)
    getNCBIProtein2NCBIGene <<- memoise::memoise(getNCBIProtein2NCBIGene, cache = cm)
    getNCBIProtein2NCBINucleotide <<- memoise::memoise(getNCBIProtein2NCBINucleotide, cache = cm)
    getNCBINucleotide2NCBIProtein <<- memoise::memoise(getNCBINucleotide2NCBIProtein, cache = cm)
    getNCBIGene2NCBINucleotide <<- memoise::memoise(getNCBIGene2NCBINucleotide, cache = cm)
    getNCBINucleotide2NCBIGene <<- memoise::memoise(getNCBINucleotide2NCBIGene, cache = cm)
    .getNCBI2UniProtDT <<- memoise::memoise(.getNCBI2UniProtDT, cache = cm)
    getNCBIIdenticalProteins <<- memoise::memoise(getNCBIIdenticalProteins, cache = cm)
    .getNCBI2UniProtBatch <<- memoise::memoise(.getNCBI2UniProtBatch, cache = cm)
    .getNCBI2UniProtIP <<- memoise::memoise(.getNCBI2UniProtIP, cache = cm)
    getNCBIProtein2UniProt <<- memoise::memoise(getNCBIProtein2UniProt, cache = cm)
    getNCBINucleotide2UniProt <<- memoise::memoise(getNCBINucleotide2UniProt, cache = cm)
    getNCBIGene2UniProt <<- memoise::memoise(getNCBIGene2UniProt, cache = cm)
    .getNCBI2KEGGDT <<- memoise::memoise(.getNCBI2KEGGDT, cache = cm)
    .getNCBI2KEGGTUP <<- memoise::memoise(.getNCBI2KEGGTUP, cache = cm)
    .getNCBI2KEGG <<- memoise::memoise(.getNCBI2KEGG, cache = cm)
    getNCBIProtein2KEGG <<- memoise::memoise(getNCBIProtein2KEGG, cache = cm)
    getNCBINucleotide2KEGG <<- memoise::memoise(getNCBINucleotide2KEGG, cache = cm)
    getNCBIGene2KEGG <<- memoise::memoise(getNCBIGene2KEGG, cache = cm)
    getNCBIProtein2CARD <<- memoise::memoise(getNCBIProtein2CARD, cache = cm)
    getNCBINucleotide2CARD <<- memoise::memoise(getNCBINucleotide2CARD, cache = cm)
    getNCBIGene2CARD <<- memoise::memoise(getNCBIGene2CARD, cache = cm)

    getCARD2NCBIProtein <<- memoise::memoise(getCARD2NCBIProtein, cache = cm)
    getCARD2NCBINucleotide <<- memoise::memoise(getCARD2NCBINucleotide, cache = cm)
    getCARD2NCBIGene <<- memoise::memoise(getCARD2NCBIGene, cache = cm)
    getCARD2UniProt <<- memoise::memoise(getCARD2UniProt, cache = cm)
    getCARD2KEGG <<- memoise::memoise(getCARD2KEGG, cache = cm)

    getKEGG2UniProt <<- memoise::memoise(getKEGG2UniProt, cache = cm)
    .getKEGG2NCBIDT <<- memoise::memoise(.getKEGG2NCBIDT, cache = cm)
    .getKEGG2NCBITUP <<- memoise::memoise(.getKEGG2NCBITUP, cache = cm)
    .getKEGG2NCBI <<- memoise::memoise(.getKEGG2NCBI, cache = cm)
    getKEGG2NCBIProtein <<- memoise::memoise(getKEGG2NCBIProtein, cache = cm)
    getKEGG2NCBINucleotide <<- memoise::memoise(getKEGG2NCBINucleotide, cache = cm)
    getKEGG2NCBIGene <<- memoise::memoise(getKEGG2NCBIGene, cache = cm)
    .getKEGG2CARDexhaustiveMappingAux <<- memoise::memoise(.getKEGG2CARDexhaustiveMappingAux, cache = cm)
    getKEGG2CARD <<- memoise::memoise(getKEGG2CARD, cache = cm)

    .getUniProt2KEGGDT <<- memoise::memoise(.getUniProt2KEGGDT, cache = cm)
    getUniProtSimilarGenes <<- memoise::memoise(getUniProtSimilarGenes, cache = cm)
    .getUniProt2KEGGSGT <<- memoise::memoise(.getUniProt2KEGGSGT, cache = cm)
    getUniProt2KEGG <<- memoise::memoise(getUniProt2KEGG, cache = cm)
    .getUniProt2NCBIDT <<- memoise::memoise(.getUniProt2NCBIDT, cache = cm)
    .getUniProt2NCBISGT <<- memoise::memoise(.getUniProt2NCBISGT, cache = cm)
    .getUniProt2NCBI <<- memoise::memoise(.getUniProt2NCBI, cache = cm)
    getUniProt2NCBIProtein <<- memoise::memoise(getUniProt2NCBIProtein, cache = cm)
    getUniProt2NCBINucleotide <<- memoise::memoise(getUniProt2NCBINucleotide, cache = cm)
    getUniProt2NCBIGene <<- memoise::memoise(getUniProt2NCBIGene, cache = cm)
    .getUniProt2CARDexhaustiveMappingAux <<- memoise::memoise(.getUniProt2CARDexhaustiveMappingAux, cache = cm)
    getUniProt2CARD <<- memoise::memoise(getUniProt2CARD, cache = cm)
}
