.onLoad = function (libname, pkgname) {
    # LRU cache of 4gb of maximum size and a day of maximum age of a translation
    cm <- cachem::cache_mem(max_size = 4096 * 1024^2, max_age = 86400, evict='lru')

    # Wrapper function to vectorize and handle single value output
    vectorizeFunction <- function(func, vargs) {
        vectorizedFunc <- Vectorize(func, vectorize.args = vargs, USE.NAMES = FALSE, SIMPLIFY = FALSE)
        return(function(...) {
            result <- vectorizedFunc(...)
            if (length(result) == 1) {
                return(result[[1]])
            } else {
                return(result)
            }
        })
    }

    getCARD2KEGG <<- memoise::memoise(getCARD2KEGG, cache = cm)
    # getCARD2KEGG <<- vectorizeFunction(getCARD2KEGG, c("cardId"))
    getCARD2KEGG <- Vectorize(getCARD2KEGG, vectorize.args = c("cardId"), USE.NAMES = FALSE, SIMPLIFY = FALSE)
    getCARD2KEGG <- return(function(cardId, exhaustiveMapping = FALSE, detailedMapping = FALSE, byIdenticalProteins = TRUE, bySimilarGenes = TRUE) {
        result <- getCARD2KEGG(cardId, exhaustiveMapping, detailedMapping, byIdenticalProteins, bySimilarGenes)
        if (length(result) == 1) {
            return(result[[1]])
        } else {
            return(result)
        }
    })

    .getNCBIDatabasesLinks <<- memoise::memoise(.getNCBIDatabasesLinks, cache = cm)
    getNCBIGene2NCBIProtein <<- memoise::memoise(getNCBIGene2NCBIProtein, cache = cm)
    getNCBIGene2NCBIProtein <<- vectorizeFunction(getNCBIGene2NCBIProtein, c("id"))
    getNCBIProtein2NCBIGene <<- memoise::memoise(getNCBIProtein2NCBIGene, cache = cm)
    getNCBIProtein2NCBIGene <<- vectorizeFunction(getNCBIProtein2NCBIGene, c("id"))
    getNCBIProtein2NCBINucleotide <<- memoise::memoise(getNCBIProtein2NCBINucleotide, cache = cm)
    getNCBIProtein2NCBINucleotide <<- vectorizeFunction(getNCBIProtein2NCBINucleotide, c("id"))
    getNCBINucleotide2NCBIProtein <<- memoise::memoise(getNCBINucleotide2NCBIProtein, cache = cm)
    getNCBINucleotide2NCBIProtein <<- vectorizeFunction(getNCBINucleotide2NCBIProtein, c("id"))
    getNCBIGene2NCBINucleotide <<- memoise::memoise(getNCBIGene2NCBINucleotide, cache = cm)
    getNCBIGene2NCBINucleotide <<- vectorizeFunction(getNCBIGene2NCBINucleotide, c("id"))
    getNCBINucleotide2NCBIGene <<- memoise::memoise(getNCBINucleotide2NCBIGene, cache = cm)
    getNCBINucleotide2NCBIGene <<- vectorizeFunction(getNCBINucleotide2NCBIGene, c("id"))
    .getNCBI2UniProtDT <<- memoise::memoise(.getNCBI2UniProtDT, cache = cm)
    getNCBIIdenticalProteins <<- memoise::memoise(getNCBIIdenticalProteins, cache = cm)
    getNCBIIdenticalProteins <<- vectorizeFunction(getNCBIIdenticalProteins, c("ncbiId"))
    .getNCBI2UniProtBatch <<- memoise::memoise(.getNCBI2UniProtBatch, cache = cm)
    .getNCBI2UniProtIP <<- memoise::memoise(.getNCBI2UniProtIP, cache = cm)
    getNCBIProtein2UniProt <<- memoise::memoise(getNCBIProtein2UniProt, cache = cm)
    getNCBIProtein2UniProt <<- vectorizeFunction(getNCBIProtein2UniProt, c("ncbiId"))
    getNCBINucleotide2UniProt <<- memoise::memoise(getNCBINucleotide2UniProt, cache = cm)
    getNCBINucleotide2UniProt <<- vectorizeFunction(getNCBINucleotide2UniProt, c("ncbiId"))
    getNCBIGene2UniProt <<- memoise::memoise(getNCBIGene2UniProt, cache = cm)
    getNCBIGene2UniProt <<- vectorizeFunction(getNCBIGene2UniProt, c("ncbiId"))
    .getNCBI2KEGGDT <<- memoise::memoise(.getNCBI2KEGGDT, cache = cm)
    .getNCBI2KEGGTUP <<- memoise::memoise(.getNCBI2KEGGTUP, cache = cm)
    .getNCBI2KEGG <<- memoise::memoise(.getNCBI2KEGG, cache = cm)
    getNCBIProtein2KEGG <<- memoise::memoise(getNCBIProtein2KEGG, cache = cm)
    getNCBIProtein2KEGG <<- vectorizeFunction(getNCBIProtein2KEGG, c("ncbiId"))
    getNCBINucleotide2KEGG <<- memoise::memoise(getNCBINucleotide2KEGG, cache = cm)
    getNCBINucleotide2KEGG <<- vectorizeFunction(getNCBINucleotide2KEGG, c("ncbiId"))
    getNCBIGene2KEGG <<- memoise::memoise(getNCBIGene2KEGG, cache = cm)
    getNCBIGene2KEGG <<- vectorizeFunction(getNCBIGene2KEGG, c("ncbiId"))
    getNCBIProtein2CARD <<- memoise::memoise(getNCBIProtein2CARD, cache = cm)
    getNCBIProtein2CARD <<- vectorizeFunction(getNCBIProtein2CARD, c("ncbiId"))
    getNCBINucleotide2CARD <<- memoise::memoise(getNCBINucleotide2CARD, cache = cm)
    getNCBINucleotide2CARD <<- vectorizeFunction(getNCBINucleotide2CARD, c("ncbiId"))
    getNCBIGene2CARD <<- memoise::memoise(getNCBIGene2CARD, cache = cm)
    getNCBIGene2CARD <<- vectorizeFunction(getNCBIGene2CARD, c("ncbiId"))

    getCARD2NCBIProtein <<- memoise::memoise(getCARD2NCBIProtein, cache = cm)
    getCARD2NCBIProtein <<- vectorizeFunction(getCARD2NCBIProtein, c("cardId"))
    getCARD2NCBINucleotide <<- memoise::memoise(getCARD2NCBINucleotide, cache = cm)
    getCARD2NCBINucleotide <<- vectorizeFunction(getCARD2NCBINucleotide, c("cardId"))
    getCARD2NCBIGene <<- memoise::memoise(getCARD2NCBIGene, cache = cm)
    getCARD2NCBIGene <<- vectorizeFunction(getCARD2NCBIGene, c("cardId"))
    getCARD2UniProt <<- memoise::memoise(getCARD2UniProt, cache = cm)
    getCARD2UniProt <<- vectorizeFunction(getCARD2UniProt, c("cardId"))

    getKEGG2UniProt <<- memoise::memoise(getKEGG2UniProt, cache = cm)
    getKEGG2UniProt <<- vectorizeFunction(getKEGG2UniProt, c("keggId"))
    .getKEGG2NCBIDT <<- memoise::memoise(.getKEGG2NCBIDT, cache = cm)
    .getKEGG2NCBITUP <<- memoise::memoise(.getKEGG2NCBITUP, cache = cm)
    .getKEGG2NCBI <<- memoise::memoise(.getKEGG2NCBI, cache = cm)
    getKEGG2NCBIProtein <<- memoise::memoise(getKEGG2NCBIProtein, cache = cm)
    getKEGG2NCBIProtein <<- vectorizeFunction(getKEGG2NCBIProtein, c("keggId"))
    getKEGG2NCBINucleotide <<- memoise::memoise(getKEGG2NCBINucleotide, cache = cm)
    getKEGG2NCBINucleotide <<- vectorizeFunction(getKEGG2NCBINucleotide, c("keggId"))
    getKEGG2NCBIGene <<- memoise::memoise(getKEGG2NCBIGene, cache = cm)
    getKEGG2NCBIGene <<- vectorizeFunction(getKEGG2NCBIGene, c("keggId"))
    .getKEGG2CARDexhaustiveMappingAux <<- memoise::memoise(.getKEGG2CARDexhaustiveMappingAux, cache = cm)
    getKEGG2CARD <<- memoise::memoise(getKEGG2CARD, cache = cm)
    getKEGG2CARD <<- vectorizeFunction(getKEGG2CARD, c("keggId"))

    .getUniProt2KEGGDT <<- memoise::memoise(.getUniProt2KEGGDT, cache = cm)
    getUniProtSimilarGenes <<- memoise::memoise(getUniProtSimilarGenes, cache = cm)
    getUniProtSimilarGenes <<- vectorizeFunction(getUniProtSimilarGenes, c("upId", "clusterIdentity"))
    .getUniProt2KEGGSGT <<- memoise::memoise(.getUniProt2KEGGSGT, cache = cm)
    getUniProt2KEGG <<- memoise::memoise(getUniProt2KEGG, cache = cm)
    getUniProt2KEGG <<- vectorizeFunction(getUniProt2KEGG, c("upId"))
    .getUniProt2NCBIDT <<- memoise::memoise(.getUniProt2NCBIDT, cache = cm)
    .getUniProt2NCBISGT <<- memoise::memoise(.getUniProt2NCBISGT, cache = cm)
    .getUniProt2NCBI <<- memoise::memoise(.getUniProt2NCBI, cache = cm)
    getUniProt2NCBIProtein <<- memoise::memoise(getUniProt2NCBIProtein, cache = cm)
    getUniProt2NCBIProtein <<- vectorizeFunction(getUniProt2NCBIProtein, c("upId"))
    getUniProt2NCBINucleotide <<- memoise::memoise(getUniProt2NCBINucleotide, cache = cm)
    getUniProt2NCBINucleotide <<- vectorizeFunction(getUniProt2NCBINucleotide, c("upId"))
    getUniProt2NCBIGene <<- memoise::memoise(getUniProt2NCBIGene, cache = cm)
    getUniProt2NCBIGene <<- vectorizeFunction(getUniProt2NCBIGene, c("upId"))
    .getUniProt2CARDexhaustiveMappingAux <<- memoise::memoise(.getUniProt2CARDexhaustiveMappingAux, cache = cm)
    getUniProt2CARD <<- memoise::memoise(getUniProt2CARD, cache = cm)
    getUniProt2CARD <<- vectorizeFunction(getUniProt2CARD, c("upId"))
}
